baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 12
#SectionPagesMenu = "main"

[params]
  title       = "Young Leader Training"
  subtitle    = "By Braid & Pentland Districts"

  cover       = "background.jpg"
  description = "Modules to do at home"
  metaDescription = "This is a website to support young leaders to continue training during social distancing. The content was put togther by the Braid and Pentland YL Training Team."
  googleAnalytics = "UA-131397022-1"
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = ""
  githubName = ""

  logo = ""
  orgName = "Website by Ryan Schuller"
  orgWebsite = "https://ryanschuller.com"
  orgDescription = ""

  author = "Ryan Schuller"
  authorAvatar = "scouts-logo.jpg"
  authorLocation = ""
  authorWebsite = ""
  authorDescription = "AESL-YL Braid"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug"
  tags = "/:slug"

[[menu.main]]
  name = "Modules"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Missions"
  url = "/missions"
  weight = 150

[[menu.main]]
  name = "Evidence"
  url = "/evidence"
  weight = 100

#[[menu.main]]
#  name = "Team"
#  url = "/team"
#  weight = 50
  