baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 9
#SectionPagesMenu = "main"

[params]
  title       = "Young Leader Training"
  subtitle    = "Modules to do at home"

  cover       = "background.jpg"
  description = "Modules to do at home"
  metaDescription = ""
  googleAnalytics = "UA-131397022-1"
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = ""
  githubName = "RyanT5/yl-training"

  logo = ""
  orgName = "Braid & Pentland YL Training Team"
  orgWebsite = ""
  orgDescription = ""

  author = "Ryan Schuller"
  authorAvatar = "ryan.jpeg"
  authorLocation = ""
  authorWebsite = ""
  authorDescription = "AESL-YL Braid"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Modules"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Missions"
  url = "/tags/missions/"
  weight = 150

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 100